name: Draft

on:
  push:
    branches: [ 'main' ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Update
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
