name: Label

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

      - name: Verify
        uses: zwaldowski/match-label-action@v5
        with:
          allowed_multiple: enhancement, bug, documentation, tests
