name: Test
run-name: "#${{ github.run_number }} test by ${{ github.triggering_actor }}"

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
  workflow_dispatch:

env:
  DOTNET_VERSION: 8
  FLUTTER_VERSION: ${{ secrets.FLUTTER_VERSION }}
  GITHUB_PAT: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
  PYTHON_VERSION: 3.12
  TEMP_FILE: tmp/output.txt
  TMS_ADAPTER_MODE: 1
  TMS_CERT_VALIDATION: false
  TMS_PRIVATE_TOKEN: ${{ secrets.TESTIT_PRIVATE_TOKEN }}
  TMS_URL: ${{ secrets.TESTIT_URL }}

jobs:
  test:
    name: ${{ matrix.project_name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - configuration_id: FLUTTER_CONFIGURATION_ID
            project_id: FLUTTER_PROJECT_ID
            project_name: FlutterTests

    env:
      TMS_CONFIGURATION_ID: ${{ secrets[matrix.configuration_id] }}
      TMS_PROJECT_ID: ${{ secrets[matrix.project_id] }}
      TMS_TEST_RUN_NAME: ${{ matrix.project_name }} TestRun

    steps:
      - name: Checkout adapters-flutter
        uses: actions/checkout@v4

      - name: Checkout api-validator-dotnet
        uses: actions/checkout@v4
        with:
          repository: testit-tms/api-validator-dotnet
          token: ${{ env.GITHUB_PAT }}
          path: api-validator-dotnet

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup environment
        run: |
          dotnet build --configuration Debug --property WarningLevel=0 api-validator-dotnet
          pip install testit-cli

      - name: Create TestRun
        run: |
          testit testrun create --token ${{ env.TMS_PRIVATE_TOKEN }} --output ${{ env.TEMP_FILE }}
          echo "TMS_TEST_RUN_ID=$(<${{ env.TEMP_FILE }})" >> $GITHUB_ENV
          echo ${{ env.TMS_TEST_RUN_ID }}

      - name: Test
        run: |
          flutter --disable-telemetry
          flutter test ./example/test/ || exit 0

      - name: Validate
        run: |
          dotnet test --configuration Debug --no-build --logger:"console;verbosity=detailed" api-validator-dotnet
